name: Build workflow

on:
  pull_request:
    branches: [ master, feature/* ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Update protos
      run: |
        sudo apt update && sudo apt install -y protobuf-compiler
        ./update.sh

    - name: Build Controller
      run: |
        cd src/controller
        go build -v .

    - name: Build Agent
      run: |
        cd src/agent
        go build -v .
